{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "packcv-ocr.fullname" . }}
  labels:
    {{- include "packcv-ocr.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  selector:
    matchLabels:
      {{- include "packcv-ocr.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: {{ .Values.serviceMonitor.path | default "/metrics" }}
      interval: {{ .Values.serviceMonitor.interval | default "30s" }}
      honorLabels: true
{{- end }}
